# Generated by Django 3.2.5 on 2021-07-22 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Historical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('miami_heat', models.IntegerField()),
                ('isPartial', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geoName', models.CharField(max_length=200)),
                ('miami_heat', models.IntegerField()),
                ('boston_celtics', models.IntegerField()),
            ],
        ),
    ]
